## Int8 Quantization

https://www.youtube.com/watch?v=IIvORO248Zs

In [8]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-1.0, 1.0, 100)
x[:10]

array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182])

In [14]:
min_x = -1
max_x = 1
qmin = -128
qmax = 127

scale = (max_x - min_x) / (qmax - qmin)
scale

0.00784313725490196

In [15]:
zero_point = 0
q = np.round((x - zero_point) / scale).astype(int)
print(q)
q = np.clip(q, qmin, qmax)
print(q)

[-128 -125 -122 -120 -117 -115 -112 -109 -107 -104 -102  -99  -97  -94
  -91  -89  -86  -84  -81  -79  -76  -73  -71  -68  -66  -63  -61  -58
  -55  -53  -50  -48  -45  -42  -40  -37  -35  -32  -30  -27  -24  -22
  -19  -17  -14  -12   -9   -6   -4   -1    1    4    6    9   12   14
   17   19   22   24   27   30   32   35   37   40   43   45   48   50
   53   55   58   61   63   66   68   71   73   76   79   81   84   86
   89   91   94   97   99  102  104  107  109  112  115  117  120  122
  125  128]
[-128 -125 -122 -120 -117 -115 -112 -109 -107 -104 -102  -99  -97  -94
  -91  -89  -86  -84  -81  -79  -76  -73  -71  -68  -66  -63  -61  -58
  -55  -53  -50  -48  -45  -42  -40  -37  -35  -32  -30  -27  -24  -22
  -19  -17  -14  -12   -9   -6   -4   -1    1    4    6    9   12   14
   17   19   22   24   27   30   32   35   37   40   43   45   48   50
   53   55   58   61   63   66   68   71   73   76   79   81   84   86
   89   91   94   97   99  102  104  107  109  112  115  117  120

## Reverse Quantization

In [17]:
x_hat = scale * (q - zero_point)
x_hat

array([-1.00392157, -0.98039216, -0.95686275, -0.94117647, -0.91764706,
       -0.90196078, -0.87843137, -0.85490196, -0.83921569, -0.81568627,
       -0.8       , -0.77647059, -0.76078431, -0.7372549 , -0.71372549,
       -0.69803922, -0.6745098 , -0.65882353, -0.63529412, -0.61960784,
       -0.59607843, -0.57254902, -0.55686275, -0.53333333, -0.51764706,
       -0.49411765, -0.47843137, -0.45490196, -0.43137255, -0.41568627,
       -0.39215686, -0.37647059, -0.35294118, -0.32941176, -0.31372549,
       -0.29019608, -0.2745098 , -0.25098039, -0.23529412, -0.21176471,
       -0.18823529, -0.17254902, -0.14901961, -0.13333333, -0.10980392,
       -0.09411765, -0.07058824, -0.04705882, -0.03137255, -0.00784314,
        0.00784314,  0.03137255,  0.04705882,  0.07058824,  0.09411765,
        0.10980392,  0.13333333,  0.14901961,  0.17254902,  0.18823529,
        0.21176471,  0.23529412,  0.25098039,  0.2745098 ,  0.29019608,
        0.31372549,  0.3372549 ,  0.35294118,  0.37647059,  0.39

In [25]:




average = abs(x - x_hat)
print(average)

add = np.sum(average) / len(average)
add

[0.00392157 0.00059418 0.00273321 0.00178253 0.00154486 0.00297089
 0.00035651 0.0036839  0.00083185 0.00249554 0.0020202  0.00130719
 0.00320856 0.00011884 0.00344623 0.00106952 0.00225787 0.00225787
 0.00106952 0.00344623 0.00011884 0.00320856 0.00130719 0.0020202
 0.00249554 0.00083185 0.0036839  0.00035651 0.00297089 0.00154486
 0.00178253 0.00273321 0.00059418 0.00392157 0.00059418 0.00273321
 0.00178253 0.00154486 0.00297089 0.00035651 0.0036839  0.00083185
 0.00249554 0.0020202  0.00130719 0.00320856 0.00011884 0.00344623
 0.00106952 0.00225787 0.00225787 0.00106952 0.00344623 0.00011884
 0.00320856 0.00130719 0.0020202  0.00249554 0.00083185 0.0036839
 0.00035651 0.00297089 0.00154486 0.00178253 0.00273321 0.00059418
 0.00392157 0.00059418 0.00273321 0.00178253 0.00154486 0.00297089
 0.00035651 0.0036839  0.00083185 0.00249554 0.0020202  0.00130719
 0.00320856 0.00011884 0.00344623 0.00106952 0.00225787 0.00225787
 0.00106952 0.00344623 0.00011884 0.00320856 0.00130719 0.002020

np.float64(0.001982174688057027)

## NF4


In [ ]:
nf4_values = np.array([-1.0, -0.75, -0.5, -0.35, -0.2, -0.1, -0.05, -0.01, 0.01, 0.05, 0.1, 0.2, 0.35, 0.5, 0.75, 1])


x = np.linspace(-1.0, 1.0, 100)
x[:10]

array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182])

In [29]:
def quantize_to_nf4(x_vals, nf4_lut):
    indices = np.argmin(np.abs(x_vals[:, None] - nf4_lut[None, :]), axis=1)
    return nf4_lut[indices]

x_nf4 = quantize_to_nf4(x, nf4_values)
x_nf4[:10]

array([-1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -1.  , -0.75, -0.75,
       -0.75])